create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  session_id uuid not null,
  run_id uuid not null,
  event_name text not null check (char_length(event_name) between 1 and 40),
  elapsed_ms integer not null default 0 check (elapsed_ms between 0 and 86400000),
  play_time_ms integer not null default 0 check (play_time_ms between 0 and 86400000),
  score integer not null default 0 check (score between 0 and 1000000),
  phase integer not null default 1 check (phase between 1 and 100000),
  zones_cleaned integer not null default 0 check (zones_cleaned between 0 and 1000000),
  device_type text not null default 'unknown' check (char_length(device_type) between 1 and 16),
  ready_time_ms integer not null default 0 check (ready_time_ms between 0 and 600000),
  utm_source text not null default '',
  utm_medium text not null default '',
  utm_campaign text not null default '',
  utm_content text not null default '',
  created_at timestamptz not null default now(),
  unique (session_id, event_name)
);

create index if not exists analytics_events_created_at_idx
  on public.analytics_events (created_at desc);

create index if not exists analytics_events_funnel_idx
  on public.analytics_events (event_name, created_at desc);

alter table public.analytics_events enable row level security;

-- No browser policies are created. Only the Vercel serverless API uses this table.
grant insert, select on table public.analytics_events to service_role;
grant usage, select on sequence public.analytics_events_id_seq to service_role;
