create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  run_id uuid not null unique,
  player_name text not null check (char_length(player_name) between 1 and 14),
  score integer not null check (score between 0 and 1000000),
  created_at timestamptz not null default now()
);

create index if not exists scores_rank_idx
  on public.scores (score desc, created_at asc);

alter table public.scores enable row level security;

-- No public policies are created. Only the Vercel API, using the service-role
-- key stored in server environment variables, can read or write scores.
